nodeLinker: node-modules

npmScopes:
  nmcore:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: true

npmRegistryServer: "https://registry.npmjs.org"
npmAuthToken: "${NODE_AUTH_TOKEN}"

npmPublishAccess: public
