blank_issues_enabled: false
contact_links:
  - name: "Have a question or want to start a discussion?"
    url: "https://github.com/muzanella11/cronmaster/discussions"
    about: "Use Discussions for questions or ideas that don’t fit into bug reports or feature requests."
