name: Build and Publish

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Sanitize Job
  sanitize:
    name: Sanitize
    uses: ./.github/workflows/sanitize.yml

  # NPM Release Job
  release:
    name: Publish
    needs: sanitize
    uses: ./.github/workflows/publish.yml

  # Create Release Notes Job
  release-notes:
    name: Release Notes
    uses: ./.github/workflows/release-notes.yml
    needs: release
