name: Build and Publish

on:
  push:
    branches:
      - main
      - develop
      - feat/cron-core
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Lint, Format, & Build Job
  lint:
    name: Lint, Format, and Build
    uses: ./.github/workflows/lint-build.yml

  # NPM Release Job
  release:
    name: Release and Publish to NPM
    needs: lint-build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Lint and Format Check
      - name: Lint and Format Check
        run: yarn lint && yarn format:check

      # Step 5: Build the Project
      - name: Build the project
        run: yarn build

      # Step 6: Release and Publish to NPM
      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Create Release Notes Job
  release-notes:
    name: Release Notes
    uses: ./.github/workflows/release-notes.yml
    needs: release
