name: Build and Publish

on:
  push:
    branches:
      - main
      - develop

    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

# permissions:
#   id-token: write # Required for OIDC
#   contents: read

jobs:
  # Sanitize Job
  sanitize:
    name: Sanitize
    uses: ./.github/workflows/sanitize.yml

  # NPM Release Job
  release:
    name: Publish
    needs: sanitize
    uses: ./.github/workflows/publish.yml

  # Create Release Notes Job
  release-notes:
    name: Release Notes
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release-notes.yml
    needs: release
