name: Publish to NPM

on: workflow_call

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  # NPM Release Job
  release:
    name: Publish to NPM
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "@nmcore"

      # Check secrets NPM TOKEN is available
      - name: Check NPM_TOKEN secret
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "Error: NPM_TOKEN secret is not set."
            exit 1
          fi

      - name: Set up NPM auth token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # - run: npm ci

      # Install NPM dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Verify dist folder exists
      - name: Verify dist folder
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder does not exist. Build the project before publishing."
            exit 1
          fi

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
