name: Publish to NPM

on: workflow_call

jobs:
  # NPM Release Job
  release:
    name: Publish to NPM
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "@nmcore"

      # Check secrets NODE_AUTH_TOKEN is available
      - name: Check NODE_AUTH_TOKEN secret
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "Error: NODE_AUTH_TOKEN secret is not set."
            exit 1
          fi

      - name: Set up NPM auth token
        run: |
          cat >> ~/.npmrc <<EOF
          //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          registry=https://registry.npmjs.org/
          always-auth=true
          EOF

      # Read .npmrc file for debugging
      - name: Read .npmrc file
        run: cat ~/.npmrc

      # - run: npm ci

      # Install NPM dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Verify dist folder exists
      - name: Verify dist folder
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder does not exist. Build the project before publishing."
            exit 1
          fi

      # Check NPM whoami
      # - name: Check NPM whoami
      #   run: npm whoami

      - run: npm ci

      # Publish to NPM
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
