name: Publish to NPM

on: workflow_call

# permissions:
#   id-token: write # Required for OIDC
#   contents: read

jobs:
  # NPM Release Job
  release:
    name: Publish to NPM
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Lint and Format Check
      - name: Lint and Format Check
        run: yarn lint && yarn format:check

      # Step 5: Build the Project
      - name: Build the project
        run: yarn build

      # Step 6: Set up NPM authentication
      - name: Set up NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Verify NPM Authentication
        run: cat ~/.npmrc

      - name: Verify Package Build
        run: ls -la ./dist

      # - name: Install NPM Package Dependencies
      #   run: npm ci

      - name: Verify NPM Login
        run: npm whoami

      # Step 7: Release and Publish to NPM
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --no-git-tag-version
