name: Release Notes

on: workflow_call

jobs:
  create-release-notes:
    name: Process Create Release Notes
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create GitHub release
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            For stable releases, please refer to [CHANGELOG.md](https://github.com/muzanella11/cronmaster/blob/main/CHANGELOG.md) for details.
            For pre-releases, please refer to [CHANGELOG.md](https://github.com/muzanella11/cronmaster/blob/final/CHANGELOG.md) of the `final` branch.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
